### ISSUE TITLE
Pilothouse Up breaks trying to load MySql 

### ISSUE THREAD

**Issue by march23** [philipnewcomer/wpdocker#107]
Hi 
When I try to install Pilothouse it complains trying to load/connect MySql, not sure why since docker compose is using Mariadb

check screenshot below

<img width="359" alt="screen shot 2018-06-26 at 2 51 44 pm" src="https://user-images.githubusercontent.com/251035/41935794-94ea568a-7950-11e8-9597-2d92864e7c9a.png">

**Comment by philipnewcomer** [comment]
In this case the name "MySQL" is hard-coded, but it refers to the database server Docker container in general whether that happens to be MySQL or MariaDB. But that's beside the point.

So the MySQL container could not be started. Open up Kitematic (which should have been installed along with Docker) and look at the logs for the `pilothouse_mysql_1` container. That should indicate why the MySQL container could not be started. The most common cause of this issue is that something on your system is already listening on port 3306. Perhaps you already have MySQL installed locally, or you have another local development environment installed that is listening on port 3306. Assuming this is the issue, shut down whatever it is that is listening on port 3306 and restart Pilothouse.

**Comment by march23** [comment]
Hi @philipnewcomer  I check the logs on Kitematic and I found:

```mysqld: unknown variable 'innodb_file_format=barracuda'```

I read a post regarding this

"innodb_file_format was deprecated in MariaDB 10.2 and removed in MariaDB 10.3.
Since MariaDB 10.2.2 the default is Barracuda, so there is no need to set this variable"

I guess a fix is coming on your last closed  [issue](https://github.com/Pilothouse-App/Pilothouse/issues/109l)

**Comment by philipnewcomer** [comment]
Yes, I just released a fix for this in version `0.14.1`. You can update to the latest version with this command: `npm update -g pilothouse`
