### ISSUE TITLE
Composer Install

### ISSUE THREAD

**Issue by mrbobbybryant** [philipnewcomer/wpdocker#72]
I tried to install this on a new computer but had issues running composer. After taking a look I noticed the repo no longer has a composer.json file. 

I went ahead and ran composer up, however it had a number of issues running.

```
/bin/sh: wp: not found
/bin/sh: wp: not found
/bin/sh: wp: not found
curl: (23) Failed writing body (0 != 12205)
sed: ./sites/sandbox/htdocs/wp-config.php: No such file or directory
```

Looks like I need to run composer install in order for the WordPress stuff to be created. Currently it is creating empty sites.

**Comment by philipnewcomer** [comment]
@mrbobbybryant It sounds like you are on the develop branch? There are some breaking changes in-progress right now on develop and some things are broken there, WP-CLI included. You should be using the master branch for production work.

BTW: Composer isn't used anymore to install WP-CLI on the host on either the master or develop branches, which is why there is no composer.json file.
