### ISSUE TITLE
Change db host in Laravel env.

### ISSUE THREAD

**Issue by mrbobbybryant** [philipnewcomer/wpdocker#74]
I had to change this from `mysql` to local host in order for the `php artisan migrate` command to work. I changed it to `127.0.0.1`.

**Comment by philipnewcomer** [comment]
@mrbobbybryant if the DB host is changed to `localhost`, then Laravel won't be able to connect to the database server during a normal web request, so that's not something we want to change.

You should be using the Pilothouse-provided `artisan` command which runs `php artisan {command}` inside the Docker container (just like the Pilothouse-provided `wp` command), instead of using your host's PHP to run Artisan outside of the Docker container. For example `artisan migrate` will run `php artisan migrate` inside the Docker container where the DB host `mysql` is valid.

**Comment by mrbobbybryant** [comment]
I too noticed that after making that change everything died a slow horrible death. This explains so much. Thanks
