### ISSUE TITLE
With pilothouse wp command, --help argument is captured by pilothouse and not wp command

### ISSUE THREAD

**Issue by chanceymathews** [philipnewcomer/wpdocker#75]
Hello,

First off, thank you so much for making this wonderful tool. It has been a great help to me. 

One issue I've run into is that when calling `wp --help` the Pilothouse command catches and handles the `--help` flag, so I can no longer read the help for individual WP-CLI commands.

Would a possible solution could be showing the Pilothouse help output followed by that from WP-CLI? If so, I could take a crack at making that happen.

Thanks!

**Comment by philipnewcomer** [comment]
Are you using the Node-based version of Pilothouse (develop branch, the one hosted on NPM)? If so, this has been fixed in the 0.8.0 release. If you're still on the old bash-based version of Pilothouse, I'd recommend updating, the Node-based version is much improved! See https://github.com/Pilothouse-App/Pilothouse/wiki/Upgrading-to-the-NodeJS-based-version-of-Pilothouse

**Comment by chanceymathews** [comment]
Thank you! I didn't realize how far behind I was. I will get it upgraded.
