### ISSUE TITLE
Unable to process Cron event

### ISSUE THREAD

**Issue by mrbobbybryant** [philipnewcomer/wpdocker#86]
Cron events do not seem to be firing. I've used WP Crontrol to see what is going on and to manually run cron events, but nothing works. Running `wp cron test` returns the following
```
WP-Cron spawn failed with error: cURL error 7: Failed to connect to radiate.dev port 80: Connection refused
```

**Comment by mrbobbybryant** [comment]
It is also worth mentioning that I get the same error when call `wp_remote_get` and passing it an image url to my local site.

Seems like we need to expose port 80 so that it can be accessed? idk

**Comment by chanceymathews** [comment]
The issue here is that the PHP container doesn't know to resolve the site's domain to the Nginx container's IP address. This prevents WP from making HTTP requests to itself, because it tries using the site's domain but there's nothing that routes that back to Nginx.

There seem to be two ways to do this:

1. [Use network links in Docker Compose](https://docs.docker.com/compose/networking/#links)
2. Add the domain names to the PHP container's hosts file

I'll try to work on this more as time allows, but this is what I found so far.

**Comment by philipnewcomer** [comment]
@chanceymathews you're absolutely right about why this is happening. I'm actually working on a fix for this right now, and I have it working locally. I'm adding entries to the hosts file, rather than using network links, since a container that uses links can't be extended, which is something I need to do for the PHP containers.

There is also an issue where when using SSL, the Pilothouse self-signed certificate is rejected by PHP, because the certificate is self-signed, thus the connection is dropped and the cron event never fires even if the PHP container's hosts file has the required entry. That is the part I am working on right now. I was able to get PHP to trust the Pilothouse SSL certificate with a bit of manual work, I just need to automate the process so it runs on `pilothouse up`.

**Comment by philipnewcomer** [comment]
WP cron events should now be working in `0.11.2`.

**Comment by chanceymathews** [comment]
This is great! Thank you!
