### ISSUE TITLE
Feature request: "Proxy" site type

### ISSUE THREAD

**Issue by spitlo** [philipnewcomer/wpdocker#93]
I really love how easy it is to set up WordPress sites with Pilothouse, but I also work with Node and Python based projects, and every time I switch to working on one of them, I have to shutdown Pilothouse and start my local Nginx to proxy these projects (to avoid port 80 conflicts). I suggest Pilothouse should have a "proxy" site type, where I could just enter the local hostname and the port on localhost to proxy to.

With Docker for Mac, this is easy since http://docker.for.mac.localhost points to the host ip. Support for that seems to be coming or has landed in Windows and Linux versions of Docker as well. Perhaps in the future Docker will provide one single cross-platform hostmachine alias. 

I've made a proof of concept fork [here](https://github.com/spitlo/Pilothouse) but I'm not sure enough I've understood all of the inner working of Pilothouse to create a pull request. I use my fork daily though, so for all my use cases it works as expected.

**Comment by philipnewcomer** [comment]
Yeah I think this could be useful to support things like Node or Python that aren't natively supported in Pilothouse. For others just tuning in, the benefits would be that one could set up a Node/Python/whatever site using whatever server the language provides, and access it using a pretty local URL like `mynodesite.dev` instead of `http://localhost:8000` or whatever the third-party server gives you. You'd be able to use Pilothouse's local SSL support with your third-party local sites.

@spitlo I'll won't be able to review your fork right away due to time constraints but I'll get to it when I can.

**Comment by philipnewcomer** [comment]
@spitlo proxy site type has been added to `0.12.0`.

**Comment by spitlo** [comment]
Great news, thank you! Will check it out when I return from vacation.
